/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blog_ihm;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Profusage extends javax.swing.JFrame {

    /**
     * Creates new form Profusage
     */
    String pdf_path = null;
    public Profusage() {
        initComponents();
        radiogroupe();
        
        qstres.getTableHeader().setFont(new Font("Calibri",Font.BOLD,19));
        qstres.getTableHeader().setForeground(new Color(0, 10, 78));
        fillqstanstable(qstres);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        blogTitle = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        subjectsection = new javax.swing.JPanel();
        addicone = new javax.swing.JLabel();
        addtitle = new javax.swing.JLabel();
        linksection = new javax.swing.JPanel();
        courseicone = new javax.swing.JLabel();
        coursetitle = new javax.swing.JLabel();
        answersection = new javax.swing.JPanel();
        helpicone = new javax.swing.JLabel();
        helptitle = new javax.swing.JLabel();
        closeandtitlepanel = new javax.swing.JPanel();
        exitbutton = new javax.swing.JLabel();
        blogcompletetitle = new javax.swing.JLabel();
        signoutlabel = new javax.swing.JLabel();
        maincontent = new javax.swing.JPanel();
        subjectpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        savesubject = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        pathlabel = new javax.swing.JLabel();
        pdftitle = new javax.swing.JTextField();
        filenamelabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tdbutton = new javax.swing.JRadioButton();
        coursebutton = new javax.swing.JRadioButton();
        exambutton = new javax.swing.JRadioButton();
        tpbutton = new javax.swing.JRadioButton();
        examcorr = new javax.swing.JRadioButton();
        linkpanel = new javax.swing.JPanel();
        linktitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        thelink = new javax.swing.JTextField();
        savelink = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        answerpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        qstres = new javax.swing.JTable();
        an = new javax.swing.JTextField();
        Addans = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 10, 78));

        blogTitle.setFont(new java.awt.Font("Calibri", 0, 29)); // NOI18N
        blogTitle.setForeground(new java.awt.Color(255, 255, 255));
        blogTitle.setText("HMI Blog");

        subjectsection.setBackground(new java.awt.Color(105, 135, 213));
        subjectsection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subjectsection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choicebutton(evt);
            }
        });

        addicone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/addsubject.png"))); // NOI18N

        addtitle.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        addtitle.setForeground(new java.awt.Color(255, 255, 255));
        addtitle.setText("Add subjects");

        javax.swing.GroupLayout subjectsectionLayout = new javax.swing.GroupLayout(subjectsection);
        subjectsection.setLayout(subjectsectionLayout);
        subjectsectionLayout.setHorizontalGroup(
            subjectsectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectsectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addicone)
                .addGap(18, 18, 18)
                .addComponent(addtitle)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        subjectsectionLayout.setVerticalGroup(
            subjectsectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subjectsectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subjectsectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, subjectsectionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addtitle))
                    .addComponent(addicone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        linksection.setBackground(new java.awt.Color(0, 10, 78));
        linksection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linksection.setPreferredSize(new java.awt.Dimension(121, 53));
        linksection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choicebutton(evt);
            }
        });

        courseicone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/link.png"))); // NOI18N

        coursetitle.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        coursetitle.setForeground(new java.awt.Color(255, 255, 255));
        coursetitle.setText("Add usefull links");

        javax.swing.GroupLayout linksectionLayout = new javax.swing.GroupLayout(linksection);
        linksection.setLayout(linksectionLayout);
        linksectionLayout.setHorizontalGroup(
            linksectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linksectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseicone)
                .addGap(18, 18, 18)
                .addComponent(coursetitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        linksectionLayout.setVerticalGroup(
            linksectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linksectionLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(linksectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coursetitle)
                    .addComponent(courseicone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        answersection.setBackground(new java.awt.Color(0, 10, 78));
        answersection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        answersection.setPreferredSize(new java.awt.Dimension(121, 53));
        answersection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choicebutton(evt);
            }
        });

        helpicone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/answerqst.png"))); // NOI18N

        helptitle.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        helptitle.setForeground(new java.awt.Color(255, 255, 255));
        helptitle.setText("Answer the questions");

        javax.swing.GroupLayout answersectionLayout = new javax.swing.GroupLayout(answersection);
        answersection.setLayout(answersectionLayout);
        answersectionLayout.setHorizontalGroup(
            answersectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answersectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpicone)
                .addGap(18, 18, 18)
                .addComponent(helptitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        answersectionLayout.setVerticalGroup(
            answersectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answersectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(answersectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(helpicone)
                    .addComponent(helptitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(blogTitle))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(subjectsection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(linksection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(answersection, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(blogTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(subjectsection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linksection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answersection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 770);

        closeandtitlepanel.setBackground(new java.awt.Color(255, 255, 255));
        closeandtitlepanel.setPreferredSize(new java.awt.Dimension(121, 53));

        exitbutton.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        exitbutton.setForeground(new java.awt.Color(0, 10, 78));
        exitbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitbutton.setText("X");
        exitbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbuttonMouseClicked(evt);
            }
        });

        blogcompletetitle.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        blogcompletetitle.setForeground(new java.awt.Color(0, 6, 103));
        blogcompletetitle.setText("Humain Machine Interaction");

        signoutlabel.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        signoutlabel.setForeground(new java.awt.Color(0, 6, 103));
        signoutlabel.setText("Sign out");
        signoutlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signoutlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signoutlabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout closeandtitlepanelLayout = new javax.swing.GroupLayout(closeandtitlepanel);
        closeandtitlepanel.setLayout(closeandtitlepanelLayout);
        closeandtitlepanelLayout.setHorizontalGroup(
            closeandtitlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeandtitlepanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(blogcompletetitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                .addComponent(signoutlabel)
                .addGap(41, 41, 41)
                .addComponent(exitbutton)
                .addGap(20, 20, 20))
        );
        closeandtitlepanelLayout.setVerticalGroup(
            closeandtitlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeandtitlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(exitbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(blogcompletetitle)
                .addComponent(signoutlabel))
        );

        getContentPane().add(closeandtitlepanel);
        closeandtitlepanel.setBounds(380, 0, 900, 50);

        maincontent.setBackground(new java.awt.Color(255, 255, 255));
        maincontent.setLayout(new java.awt.CardLayout());

        subjectpanel.setBackground(new java.awt.Color(255, 255, 255));
        subjectpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choicebutton(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 6, 103));
        jLabel1.setText("Add Subject");

        savesubject.setBackground(new java.awt.Color(255, 255, 255));
        savesubject.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        savesubject.setForeground(new java.awt.Color(68, 91, 193));
        savesubject.setText("Save");
        savesubject.setBorder(null);
        savesubject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savesubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savesubjectActionPerformed(evt);
            }
        });

        addbutton.setBackground(new java.awt.Color(255, 255, 255));
        addbutton.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        addbutton.setForeground(new java.awt.Color(68, 91, 193));
        addbutton.setText("Add pdf file");
        addbutton.setBorder(null);
        addbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addfilebutton(evt);
            }
        });

        pathlabel.setFont(new java.awt.Font("Calibri", 0, 19)); // NOI18N
        pathlabel.setText("                                                     ");

        pdftitle.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        pdftitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 91, 193)));

        filenamelabel.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        filenamelabel.setForeground(new java.awt.Color(0, 6, 103));
        filenamelabel.setText("The file name");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Note : Please write in the textfiled section the name of the file and pdf extension");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("for example : course.pdf");

        tdbutton.setBackground(new java.awt.Color(255, 255, 255));
        tdbutton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        tdbutton.setForeground(new java.awt.Color(2, 3, 145));
        tdbutton.setText("TD");

        coursebutton.setBackground(new java.awt.Color(255, 255, 255));
        coursebutton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        coursebutton.setForeground(new java.awt.Color(2, 3, 145));
        coursebutton.setText("Course");

        exambutton.setBackground(new java.awt.Color(255, 255, 255));
        exambutton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        exambutton.setForeground(new java.awt.Color(2, 3, 145));
        exambutton.setText("Exam");

        tpbutton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        tpbutton.setForeground(new java.awt.Color(2, 3, 145));
        tpbutton.setText("TP");

        examcorr.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        examcorr.setForeground(new java.awt.Color(2, 3, 145));
        examcorr.setText("Exam Correction");

        javax.swing.GroupLayout subjectpanelLayout = new javax.swing.GroupLayout(subjectpanel);
        subjectpanel.setLayout(subjectpanelLayout);
        subjectpanelLayout.setHorizontalGroup(
            subjectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subjectpanelLayout.createSequentialGroup()
                .addGap(0, 146, Short.MAX_VALUE)
                .addGroup(subjectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(subjectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subjectpanelLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(151, 151, 151))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subjectpanelLayout.createSequentialGroup()
                            .addComponent(pathlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)))))
            .addGroup(subjectpanelLayout.createSequentialGroup()
                .addGroup(subjectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subjectpanelLayout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addGroup(subjectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(subjectpanelLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(subjectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filenamelabel)
                            .addComponent(pdftitle, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(subjectpanelLayout.createSequentialGroup()
                                .addGroup(subjectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(subjectpanelLayout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(savesubject, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(subjectpanelLayout.createSequentialGroup()
                                        .addComponent(coursebutton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(exambutton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tdbutton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tpbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(examcorr)))))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        subjectpanelLayout.setVerticalGroup(
            subjectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectpanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(pathlabel)
                .addGap(18, 18, 18)
                .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(filenamelabel)
                .addGap(18, 18, 18)
                .addComponent(pdftitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(subjectpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coursebutton)
                    .addComponent(tdbutton)
                    .addComponent(exambutton)
                    .addComponent(tpbutton)
                    .addComponent(examcorr))
                .addGap(19, 19, 19)
                .addComponent(savesubject, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        maincontent.add(subjectpanel, "card2");

        linkpanel.setBackground(new java.awt.Color(255, 255, 255));

        linktitle.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        linktitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 91, 193)));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 19)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 6, 103));
        jLabel4.setText("Link title");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 6, 103));
        jLabel5.setText("The Link");

        thelink.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        thelink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 91, 193)));

        savelink.setBackground(new java.awt.Color(255, 255, 255));
        savelink.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        savelink.setForeground(new java.awt.Color(68, 91, 193));
        savelink.setText("Save");
        savelink.setBorder(null);
        savelink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savelink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savelinkMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 6, 103));
        jLabel6.setText("Help students to expand their knowledge by adding article and vedio links");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 19)); // NOI18N
        jLabel7.setText("Note : please make sure that you add the type of the link after the link title ");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 19)); // NOI18N
        jLabel8.setText("for example : waht is HMI youtube vedio ");

        javax.swing.GroupLayout linkpanelLayout = new javax.swing.GroupLayout(linkpanel);
        linkpanel.setLayout(linkpanelLayout);
        linkpanelLayout.setHorizontalGroup(
            linkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkpanelLayout.createSequentialGroup()
                .addGroup(linkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(linkpanelLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addGroup(linkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thelink, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(linktitle, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(linkpanelLayout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(savelink, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(linkpanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(linkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        linkpanelLayout.setVerticalGroup(
            linkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linkpanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel6)
                .addGap(51, 51, 51)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linktitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thelink, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(savelink, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(153, 153, 153))
        );

        maincontent.add(linkpanel, "card3");

        answerpanel.setBackground(new java.awt.Color(255, 255, 255));

        qstres.setFont(new java.awt.Font("Calibri", 1, 19)); // NOI18N
        qstres.setForeground(new java.awt.Color(0, 10, 78));
        qstres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question"
            }
        ));
        qstres.setRowHeight(26);
        qstres.setSelectionBackground(new java.awt.Color(105, 135, 213));
        jScrollPane2.setViewportView(qstres);

        an.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        an.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 91, 193)));

        Addans.setBackground(new java.awt.Color(255, 255, 255));
        Addans.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        Addans.setForeground(new java.awt.Color(68, 91, 193));
        Addans.setText("Add an answer");
        Addans.setBorder(null);
        Addans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddansMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 19)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 6, 103));
        jLabel10.setText("The Answer :");

        javax.swing.GroupLayout answerpanelLayout = new javax.swing.GroupLayout(answerpanel);
        answerpanel.setLayout(answerpanelLayout);
        answerpanelLayout.setHorizontalGroup(
            answerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerpanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answerpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(answerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answerpanelLayout.createSequentialGroup()
                        .addGroup(answerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(an, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answerpanelLayout.createSequentialGroup()
                        .addComponent(Addans, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(361, 361, 361))))
        );
        answerpanelLayout.setVerticalGroup(
            answerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(an, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Addans, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        maincontent.add(answerpanel, "card4");

        getContentPane().add(maincontent);
        maincontent.setBounds(380, 50, 900, 720);

        setSize(new java.awt.Dimension(1274, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbuttonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbuttonMouseClicked

    private void signoutlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutlabelMouseClicked
        // TODO add your handling code here:
        HomePage homepage=new HomePage();
        homepage.setVisible(true);
        homepage.setLocationRelativeTo(null);
        homepage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_signoutlabelMouseClicked

    private void choicebutton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choicebutton
        // TODO add your handling code here:
         if(evt.getSource()==subjectsection){
            subjectpanel.setVisible(true);
            linkpanel.setVisible(false);
            answerpanel.setVisible(false);
            
            subjectsection.setBackground(new java.awt.Color(105, 135, 213));
            linksection.setBackground(new java.awt.Color(0, 10, 78));
            answersection.setBackground(new java.awt.Color(0, 10, 78));
        }
         if(evt.getSource()==linksection){
            subjectpanel.setVisible(false);
            linkpanel.setVisible(true);
            answerpanel.setVisible(false);
            
            
            subjectsection.setBackground(new java.awt.Color(0, 10, 78));
            linksection.setBackground(new java.awt.Color(105, 135, 213));
            answersection.setBackground(new java.awt.Color(0, 10, 78));
          
        }
         if(evt.getSource()==answersection){
            subjectpanel.setVisible(false);
            linkpanel.setVisible(false);
            answerpanel.setVisible(true);
            
            subjectsection.setBackground(new java.awt.Color(0, 10, 78));
            linksection.setBackground(new java.awt.Color(0, 10, 78));
            answersection.setBackground(new java.awt.Color(105, 135, 213));
         }
    }//GEN-LAST:event_choicebutton

    private void savesubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savesubjectActionPerformed
        // TODO add your handling code here:
        DB_Operation db = new DB_Operation();
        String pdf_title = pdftitle.getText();
        
        if(!coursebutton.isSelected() && !exambutton.isSelected() && !tdbutton.isSelected() && !tpbutton.isSelected() && !examcorr.isSelected() && pdf_title.trim().equals("")){
            JOptionPane.showMessageDialog(null, "You have fill the fields", "Empty fiels", 2);
        }
        else if(pdf_title.trim().equals("")){
            JOptionPane.showMessageDialog(null, "You have to put a file name ", "Empty field", 2);
        }
        else if(!coursebutton.isSelected() && !exambutton.isSelected() && !tdbutton.isSelected() && !tpbutton.isSelected() && !examcorr.isSelected()){
            JOptionPane.showMessageDialog(null, "You have to choose one section", "Empty field", 2);
        }
            if(coursebutton.isSelected()){
              PreparedStatement ps = null;
              String search = "SELECT * FROM files WHERE title='"+pdf_title+"'";
              ResultSet rs = db.searchQuery(search);
            try {
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "This course already exist", "Course Exist", 2);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
              String query="INSERT INTO `files`(`title`, `pdf`) VALUES (?,?)";
            try {
                ps=db.getConnection().prepareStatement(query);
                ps.setString(1, pdf_title);
                
                try {
                    //save the pdf as a blob in the database
                    if(pdf_path!=null){
                       InputStream pdf = new FileInputStream(new File(pdf_path));
                       ps.setBlob(2, pdf);    
                    }
                    ps.execute();
                    
                    JOptionPane.showMessageDialog(null,"The course is uploaded successfuly");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Profusage.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Profusage.class.getName()).log(Level.SEVERE, null, ex);
            }    
            }
            if(exambutton.isSelected()){
                PreparedStatement ps = null;
                String search = "SELECT * FROM exam WHERE examtitle='"+pdf_title+"'";
              ResultSet rs = db.searchQuery(search);
            try {
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "This exam already exist", "Exam Exist", 2);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
                String query="INSERT INTO `exam`(`examtitle`, `exampdf`) VALUES (?,?)";
            try {
                ps=db.getConnection().prepareStatement(query);
                ps.setString(1, pdf_title);
                
                try {
                    //save the pdf as a blob in the database
                    if(pdf_path!=null){
                       InputStream pdf = new FileInputStream(new File(pdf_path));
                       ps.setBlob(2, pdf);    
                    }
                    ps.execute();
                    
                    JOptionPane.showMessageDialog(null,"The exam is uploaded successfuly");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Profusage.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Profusage.class.getName()).log(Level.SEVERE, null, ex);
            }    
            }
            
            if(tdbutton.isSelected()){
                PreparedStatement ps = null;
                String search = "SELECT * FROM td WHERE tdtitle='"+pdf_title+"'";
              ResultSet rs = db.searchQuery(search);
            try {
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "This td already exist", "Td Exist", 2);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
                String query="INSERT INTO `td`(`tdtitle`, `tdpdf`) VALUES (?,?)";
            try {
                ps=db.getConnection().prepareStatement(query);
                ps.setString(1, pdf_title);
                
                try {
                    //save the pdf as a blob in the database
                    if(pdf_path!=null){
                       InputStream pdf = new FileInputStream(new File(pdf_path));
                       ps.setBlob(2, pdf);    
                    }
                    ps.execute();
                    
                    JOptionPane.showMessageDialog(null,"The td is uploaded successfuly");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Profusage.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Profusage.class.getName()).log(Level.SEVERE, null, ex);
            }    
            }
            
            if(tpbutton.isSelected()){
                PreparedStatement ps = null;
                String search = "SELECT * FROM tp WHERE tptitle='"+pdf_title+"'";
              ResultSet rs = db.searchQuery(search);
            try {
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "This tp already exist", "Tp Exist", 2);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
                String query="INSERT INTO `tp`(`tptitle`, `tppdf`) VALUES (?,?)";
            try {
                ps=db.getConnection().prepareStatement(query);
                ps.setString(1, pdf_title);
                
                try {
                    //save the pdf as a blob in the database
                    if(pdf_path!=null){
                       InputStream pdf = new FileInputStream(new File(pdf_path));
                       ps.setBlob(2, pdf);    
                    }
                    ps.execute();
                    
                    JOptionPane.showMessageDialog(null,"The tp is uploaded successfuly");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Profusage.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Profusage.class.getName()).log(Level.SEVERE, null, ex);
            }    
            }
            
            if(examcorr.isSelected()){
                PreparedStatement ps = null;
                String search = "SELECT * FROM examensol WHERE soltitle='"+pdf_title+"'";
              ResultSet rs = db.searchQuery(search);
            try {
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "This exam correction already exist", "Exam correction Exist", 2);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
                String query="INSERT INTO `examensol`(`soltitle`, `solpdf`) VALUES (?,?)";
            try {
                ps=db.getConnection().prepareStatement(query);
                ps.setString(1, pdf_title);
                
                try {
                    //save the pdf as a blob in the database
                    if(pdf_path!=null){
                       InputStream pdf = new FileInputStream(new File(pdf_path));
                       ps.setBlob(2, pdf);    
                    }
                    ps.execute();
                    
                    JOptionPane.showMessageDialog(null,"The exam correction is uploaded successfuly");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Profusage.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Profusage.class.getName()).log(Level.SEVERE, null, ex);
            }    
            }
            
            if(pathlabel.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "You have to choose a file that exist on your local storage", "choose a file", 2);
            }
            
    }//GEN-LAST:event_savesubjectActionPerformed

    private void addfilebutton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfilebutton
        // TODO add your handling code here:
        String path = null;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(null);
        FileNameExtensionFilter extension = new FileNameExtensionFilter("PdfFiles","pdf");
        chooser.addChoosableFileFilter(extension);
        
        int filestate = chooser.showSaveDialog(null);
        if(filestate == JFileChooser.APPROVE_OPTION){
            File selectedpdf = chooser.getSelectedFile();
            path = selectedpdf.getAbsolutePath();
            pathlabel.setText(path);
            
            pdf_path = path;
            
 
        }
        
    }//GEN-LAST:event_addfilebutton

    private void savelinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savelinkMouseClicked
        // TODO add your handling code here:
        String lt = linktitle.getText();
        String li = thelink.getText();
        DB_Operation db = new DB_Operation();
        
        if(verifyfields()){
            try {
                ResultSet rs = db.searchQuery("SELECT * FROM link WHERE thelink='"+li+"'");
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "This link already exist", "choose another link", 2);
                }else{
                    db.Insert("INSERT INTO `link`(`linktitle`, `thelink`) VALUES ('"+lt+"','"+li+"')");
                    JOptionPane.showMessageDialog(null, "This link is addes successfuly");
                }
              
            } catch (SQLException ex) {
                Logger.getLogger(Profusage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_savelinkMouseClicked

    int rowindex=-1;
    private void AddansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddansMouseClicked
        // TODO add your handling code here:
  
        String answer = an.getText();
        int rowindex = qstres.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) qstres.getModel();
        if(rowindex == -1 && answer.trim().equals("")){
          JOptionPane.showMessageDialog(null, "You must choose a question and write the answer for it", "Empty feilds", 2);  
        }
        else if(rowindex == -1){
            JOptionPane.showMessageDialog(null, "You must choose a question", "Choose a question", 2);
        }else if(answer.trim().equals("")){
          JOptionPane.showMessageDialog(null, "You must write an answer for the choosen question", "Answer The Question", 2);  
        }
        else{
            String question = model.getValueAt(rowindex,0).toString();
           DB_Operation db = new DB_Operation();
           ResultSet rs = db.searchQuery("SELECT * FROM question WHERE qst='"+question+"'");
            try {
                if(rs.next()){
                    boolean manswer = rs.getString(2).equals("");
                    if(manswer){
                        db.Update("UPDATE `question` SET `ans`='"+answer+"' WHERE `qst`='"+question+"'");
                        JOptionPane.showMessageDialog(null, "The operation is done successfuly");
                        an.setText("");
                       
                    }else{
                        JOptionPane.showMessageDialog(null, "The answer for this question already exist", "Answer Exist", 2);
                    }
                }} catch (SQLException ex) {
                Logger.getLogger(Profusage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_AddansMouseClicked
    public void radiogroupe(){
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(coursebutton);
        bg1.add(exambutton);
        bg1.add(tdbutton);
        bg1.add(tpbutton);
        bg1.add(examcorr);
    }
    
    public boolean verifyfields(){
        String lt = linktitle.getText();
        String li = thelink.getText();
        
        if(lt.trim().equals("") || li.trim().equals("")){
            JOptionPane.showMessageDialog(null, "One or more fields are empty","Empty fields",2);
            return false;
        }else {
            return true;
        }
    }
    
    public void fillqstanstable(JTable table){
        try {
            DB_Operation db = new DB_Operation();
            Connection con = db.getConnection();
            PreparedStatement ps;
            ps = con.prepareStatement("SELECT * FROM `question`");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            
            Object[] row;
            while(rs.next()){
                row = new Object[1];
                row[0]= rs.getString(1);
                model.addRow(row);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profusage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profusage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profusage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profusage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profusage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addans;
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton addbutton;
    private javax.swing.JLabel addicone;
    private javax.swing.JLabel addtitle;
    private javax.swing.JTextField an;
    private javax.swing.JPanel answerpanel;
    private javax.swing.JPanel answersection;
    private javax.swing.JLabel blogTitle;
    private javax.swing.JLabel blogcompletetitle;
    private javax.swing.JPanel closeandtitlepanel;
    private javax.swing.JRadioButton coursebutton;
    private javax.swing.JLabel courseicone;
    private javax.swing.JLabel coursetitle;
    private javax.swing.JRadioButton exambutton;
    private javax.swing.JRadioButton examcorr;
    private javax.swing.JLabel exitbutton;
    private javax.swing.JLabel filenamelabel;
    private javax.swing.JLabel helpicone;
    private javax.swing.JLabel helptitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel linkpanel;
    private javax.swing.JPanel linksection;
    private javax.swing.JTextField linktitle;
    private javax.swing.JPanel maincontent;
    private javax.swing.JLabel pathlabel;
    private javax.swing.JTextField pdftitle;
    private javax.swing.JTable qstres;
    private javax.swing.JButton savelink;
    private javax.swing.JButton savesubject;
    private javax.swing.JLabel signoutlabel;
    private javax.swing.JPanel subjectpanel;
    private javax.swing.JPanel subjectsection;
    private javax.swing.JRadioButton tdbutton;
    private javax.swing.JTextField thelink;
    private javax.swing.JRadioButton tpbutton;
    // End of variables declaration//GEN-END:variables
}
